### ISSUE TITLE
Make phantomjs dependency optional

### ISSUE THREAD

**Issue by Aareksio** [rimiti/invoice-it#25]
Hi!

Is there a chance you could make phantomjs (html-to-pdf) dependency optional? I'd like to use your library just to generate HTML invoices and PhantomJS is too big of a dependency for such use case (not to mention it is deprecated).

Regards

**Comment by rimiti** [comment]
Hello @Aareksio,

It's a good idea, could you create a PR ?  👍 

Regards, 🚀

**Comment by rimiti** [comment]
@Aareksio You PR has been merge.

Thank you for you contribution 🚀
