### ISSUE TITLE
How to change the reference of invoice

### ISSUE THREAD

**Issue by dinhdangkhoa** [rimiti/invoice-it#34]
Hi,
First of all, thank you for this package. It helped me a lot !

Could you please show me how to change the reference of invoice ? I saved the information 
 of transaction in database and now I want to put the key of transaction in this place. Is this possible ?
Thank you.
![image](https://user-images.githubusercontent.com/26383263/57141078-b3892e00-6db9-11e9-838a-605ddffbd372.png)

**Comment by rimiti** [comment]
Hello @dinhdangkhoa,

I've updated the [README](https://github.com/rimiti/invoice-it/tree/update-documentation-examples), it should be more clear, no?

**Comment by kafkaman-labs** [comment]
Same problem :/
