### ISSUE TITLE
Cannot read property '_handle' of undefined

### ISSUE THREAD

**Issue by Pangolino91** [rimiti/invoice-it#38]
Just ran the normal sample on your npm page, throws this error. 
I did some searches it says it is due to an old express.js configuration

**Comment by rimiti** [comment]
Thanks @Pangolino91 for this issue,

Could you please share us the complet stack trace with this context (node version / OS / ...à ?

**Comment by ThomasGuoItaly** [comment]
Cannot read property '_handle' of undefined...... windows 10, 64bit

**Comment by Pangolino91** [comment]
I am sorry for being newbie, I was not using Node....I was only using
Python, thats why it wasw not working

Il giorno lun 22 lug 2019 alle ore 21:46 Thomas <notifications@github.com>
ha scritto:

**Comment by rimiti** [comment]
Aha! :trollface: 

Don't worries and be welcome into this amazing community! 🙏
