### ISSUE TITLE
undefined for invoice.getInvoice().toPDF().toBuffer()

### ISSUE THREAD

**Issue by vishvendrasingh** [rimiti/invoice-it#45]
unable to create buffer

`const invoiceIt = require('@rimiti/invoice-it').default;

  const recipient = {
    company_name: 'Receiver company',
    first_name: 'Will',
    last_name: 'Jameson',
    street_number: '20',
    street_name: 'Rue Victor Hugo',
    zip_code: '77340',
    city: 'Pontault-Combault',
    country: 'France',
    phone: '06 00 00 00 00',
    mail: 'will.jameson@test.com'
  };

  const emitter = {
    name: 'Dim Solution',
    street_number: '15',
    street_name: 'Rue Jean Jaures',
    zip_code: '75012',
    city: 'Paris',
    country: 'France',
    phone: '01 00 00 00 00',
    mail: 'contact@dimsolution.com',
    website: 'www.dimsolution.com'
  };

  const invoice = invoiceIt.create(recipient, emitter);
const pdf = invoice.getInvoice().toPDF().toBuffer()
const pdf = invoice.getInvoice().toPDF()
// .toFile('./invoice.pdf')
//   .then((r) => {
//       console.log('PDF file created.',r);
//       });
    console.log(pdf)`

**Comment by rimiti** [comment]
Oh! Can you create a PR to fix that ?

**Comment by vishvendrasingh** [comment]
sure @rimiti  will do. One more question is there any option to update `table_information`?

**Comment by vishvendrasingh** [comment]
below generates the buffer, please tell me in which file do you want me to place this code?

`const HtmlPDF = require('html-pdf');
await new Promise((resolve, reject) => { HtmlPDF.create(html).toBuffer(function(err, buffer){ resolve(buffer) } ) } `

**Comment by diffusi-on** [comment]
What about fix?

**Comment by diffusi-on** [comment]
Fix pelase.

src/generator.js

`
  _toBufferFromPDF(content) {
    return content.toBuffer((err, buffer) => {
      if (err) throw new Error(err);
      return buffer;
    });
  }
`
Should be replaced to

`
  _toBufferFromPDF(content) {
    return new Promise((resolve, reject) => content.toBuffer((err, buffer) => {
      if (err) return reject(err);
      return resolve(buffer);
    }));
  }
`

**Comment by diffusi-on** [comment]
@rimiti 

PR for this fix https://github.com/rimiti/invoice-it/pull/46

**Comment by rimiti** [comment]
Thanks for you contribution. It has been released.

🙏
