### ISSUE TITLE
Not compatible with React

### ISSUE THREAD

**Issue by angeligareta** [rimiti/invoice-it#50]
Hi, I am having this issue when using it on React: 
`Module not found: Can't resolve 'fs' in '/home/angeligareta/Desktop/Atecresa/ecommerce/node_modules/@rimiti/invoice-it/dist/classes'`

This module does not have an option to be compatible with browser?

Regards

**Comment by rimiti** [comment]
That's normal, this package cannot be use in front. It's a "backend" package.

**Comment by angeligareta** [comment]
Okay, I would have liked it to be compatible with front also, instead of using fs having an option to return the generated document.
